config/routes.rb
Rails.application.routes.draw do
   root 'recipes#index'
   resources :users, only: [:new, :create]
   resource :session, only: [:new, :create, :destroy] 

   resources :recipes do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
   end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.is_admin? 
      can :manage, :all 
    end

    alias_action :create, :read, :update, :destroy, to: :crud

    can(:crud, Recipe) do |recipe|
      recipe.user == user # current_user
    end

    can(:crud, Comment) do |comment|
      comment.user == user # current_user
    end


    can :like, Recipe do |recipe|
      user.present? && recipe.user != user
    end

    can :destroy, Like  do |like|
      like.user == user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :body, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :comments, dependent: :destroy

    belongs_to :user

    validates :title, presence: true

    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :recipes
    has_many :comments

    has_many :likes, dependent: :destroy
    has_many :liked_recipes, through: :likes, source: :recipe

    validates :email, presence: true, uniqueness: true,
    format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    def full_name
        "#{first_name} #{last_name}"
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find session[:user_id] 
    end
  end
  helper_method :current_user
 
  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def authenticate_user!
    unless user_signed_in?
      flash[:danger] = "You need to be signed in first!"
      redirect_to new_session_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @recipe = Recipe.find params[:recipe_id]
        comment_params = params.require(:comment).permit(:body)
        @comment = Comment.new comment_params
        @comment.recipe  = @recipe
        @comment.user = current_user
        if @comment.save
          redirect_to recipe_path(@recipe), notice: "Comment created"
        else
          @comments=@recipe.comments.order(created_at: :desc)
          render "/recipes/show"
        end
      end

      def destroy 
        @comment = Comment.find params[:id]
        if can?(:crud, @comment)
            @comment.destroy 
            redirect_to recipe_path(@comment.recipe)
        else 
            head :unauthorized
        end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy] 
 
  def create
    recipe = Recipe.find params[:recipe_id]
    like = Like.new(recipe: recipe, user: current_user)

    if !can?(:like, recipe)
        flash[:danger] = "You can't like your own recipe...."
      elsif like.save
        flash[:success] = "Recipe Liked"
      else
        flash[:danger] = like.errors.full_messages.join(", ")
      end
      redirect_to recipe_path(recipe)
  end
 
  def destroy
    like = current_user.likes.find params[:id]
    like.destroy
    redirect_to recipe_path(like.recipe), notice: "Unliked"
  end
 

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize!, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.all.order('updated_at DESC') 
  end
 
  def new
    @recipe = Recipe.new
  end
 
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipes_path, notice: "Recipe Created"
    else
      render :new
    end
  end
 
  def show
    id = params[:id]
    @recipe = Recipe.find(id)
    @comment = Comment.new
    @comments = @recipe.comments.order(created_at: :desc)
    @like = @recipe.likes.find_by(user: current_user)

  end
 
  def edit
  end
 
  def update

    id = params[:id]
    @recipe = Recipe.find(id)

    if @recipe.update recipe_params
      redirect_to recipe_path(@recipe), notice: "Recipe Updated"
    else
      render :edit
    end
  end
 
  def destroy

    id = params[:id]
    @recipe = Recipe.find(id)
    @recipe.destroy
    redirect_to recipes_path, notice: "Recipe Deleted"
  end
 
  private
 
  def find_recipe
    @recipe = Recipe.find params[:id]
  end
 
  def recipe_params
    params.require(:recipe).permit(:title, :body)
  end

  def authorize! 
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @recipe)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email params[:email]
   
    if user&.authenticate params[:password]
      session[:user_id] = user.id
      flash[:success] = "User Logged In"
      redirect_to recipes_path
    else
      flash[:warning] = "Please Check your Credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to recipes_path
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
      end
     
      def create
        @user = User.new user_params
        if @user.save
          session[:user_id] = @user.id
          redirect_to recipes_path, notice: "Logged In!"
        else
          render :new
        end
      end
     
      private
     
      def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
 <%= render 'shared/navbar' %>
    <div class="flash">
      <% flash.each do |type, message| %>
        <div class='bg-<%= type %> p-3 rounded mb-2 shadow-sm'>
          <%= message %>
    </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if @recipe.errors.present? %>
  <p>
    <%= @recipe.errors.full_messages.join(', ')%>
  </p>
<% end %>

<div class='show-container'>

  <%= form_with model: @recipe, local:true do |f| %>
    <div class='form-group'>
      <%= f.label :title %>
      <%= f.text_field(:title, class: 'form-control')%>
    </div>
    <div class='form-group'>
      <%= f.label :body %>
      <%= f.text_area(:body, class: 'form-control', cols: 50, rows: 5)%>
    </div>

    <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/recipes/edit.html.erb
<h1 class="heading">Edit Recipe Page</h1>
<%= render "form" %>

app/views/recipes/index.html.erb
<div> 
  <ul class="index-list">
    <% @recipes.each do |recipe|  %>
      <div class="index-text"> 
        <li class='list-item'>
          <h2 class="index-title"><%= link_to recipe.title, recipe_path(recipe) %></h2>

          <p><%= recipe.body %></p>
          </li>
           <div class="user-like-info">
          <span class="user-link">By <%= recipe.user.first_name %> <%= recipe.user.last_name %> </span>
          <span>Likes: <%= recipe.likes.count %></span>
          </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<h1 class="heading">New Recipe Page</h1>
<%= render "form" %>

app/views/recipes/show.html.erb
<div class='show-container'>
    <div class=show-bk>
      <h1 class="show-title">
        <%= @recipe.title %>
      </h1>
      <p class='show-text'><%= @recipe.body %></p>
      <p><%= @recipe.created_at %></p>
    </div>

  <span class="show-user">Liked by: <%= @recipe.likes.count %></span>
  <span class="btn btn-shadow">
    <% if @like.present? && @like.persisted? %>
      <%= link_to "Un-Like", recipe_like_path(@recipe, @like), method: :delete %>
    <% else %>
      <%= link_to "Like", recipe_likes_path(@recipe), method: :post %>
    <% end %>
  </span>

  <% if can? :edit, @recipe %>
    <%= link_to "Edit", edit_recipe_path(@recipe),class: 'btn btn-shadow show-btn' %>
  <% end %>
  <% if can? :destroy, @recipe %>
    <%= link_to "Delete", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?"},class: 'btn btn-shadow show-btn' %>
  <% end %>
  <hr>
</div>

<div class='show-container'>
    <h2>Add a comment</h2>
    <% if @comment.errors.any? %>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li  class="text-danger"><%= msg %><li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for [@recipe, @comment] do |f| %>
       <div class="form-group">
      <%= f.text_area(
        :body,
        cols: 10,
        rows: 3,
        placeholder: "Write your Comments!",
        class: "form-control"
      ) %>
    </div>
      <%= f.submit "Comment", class: "btn btn-shadow"  %>
    <% end %>
  <div>
   <ul class="index-list">
      <h2>Comments</h2>
      <% @recipe.comments.each do |comment| %>
        <div class="index-text">
          <li class="list-item">
            <p class='show-text'>
                  <%= comment.body %><br />
                  <% if can? :crud, comment %>
                  <small>
                    <%= link_to(
                      "Delete",
                      recipe_comment_path(@recipe, comment),
                      method: :delete, 
                      data: {
                        confirm: "Are you sure?"
                      },
                      class: 'btn btn-shadow show-btn btn-sm',
                    ) %>
                  </small>
                  |
                  <% end %>
                  <small>
                    commented <%= time_ago_in_words(comment.created_at) %> by <%= comment.user.full_name %> <%= comment.user.last_name %>
                  </small>
              </p>
          </li>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class='navbar'>
  <ul class='navbar-nav mr-auto'>

    <div class="logo"><%= image_tag "recipe.png", class: "recipe-img"%>
    <h5><%= link_to "All Recipes", root_path, class: 'home-btn'%></h5>
     <%= link_to "Add Recipes", new_recipe_path, class: 'btn btn-shadow'%>

    </div>
  </ul>
  <div class="nav-item">
  <div>
    <% if user_signed_in? %>
     <span class="user"><%= current_user.first_name %> <%= current_user.last_name %></span> 
      <%= link_to "Logout", session_path, method: :delete, class: 'btn btn-shadow' %>
    <% else %> 
      <span class="log-btns"><%= link_to "Sign In", new_session_path, class: 'btn btn-shadow'%></span>
      <span class="log-btns"><%= link_to "New Account", new_user_path, class: 'btn btn-shadow'%></span>
    <% end %>
  </div>
 
  </div>
</nav>

app/views/users/new.html.erb
<h1 class="heading">User New Page</h1>
<% if @user.errors.present? %>
  <p>
    <%= @user.errors.full_messages.join(', ')%>
  </p>
<% end %>
<div class='show-container'>
  <%= form_with model: @user, local: true do |f| %>
    <div class='form-group'>
      <%= f.label :first_name%>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :last_name%>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :email%>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password%>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit "Create User", class: 'btn btn-shadow' %>
  <% end %>
</div>